apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deloy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
        volumeMounts:
        - name: prometheus-vol
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-vol
        configMap:
          name: prometheus_vol

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
data:
  prometheus_vol: prom_vol